apiVersion: v1
kind: Secret
metadata:
  name: meatmanager-api-secret
  namespace: meatmanager
stringData:
  DB_USER: "root"
  DB_PASS: "cambiar_password"
  CLIENTS_DB_USER: "root"
  CLIENTS_DB_PASS: "cambiar_password"
  SMTP_HOST: "smtp.tu-servidor.com"
  SMTP_PORT: "587"
  SMTP_USER: "tu_usuario_smtp"
  SMTP_PASS: "tu_password_smtp"
  SMTP_FROM: "MeatManager <no-reply@tudominio.com>"
  CASH_WITHDRAWAL_CODE_TTL_MINUTES: "10"
  REDIS_PASS: "tu_password_redis"
  firebase-service-account.json: |
    {
      "type": "service_account",
      "project_id": "tu-project-id",
      "private_key_id": "cambiar",
      "private_key": "-----BEGIN PRIVATE KEY-----\ncambiar\n-----END PRIVATE KEY-----\n",
      "client_email": "firebase-adminsdk@tu-project.iam.gserviceaccount.com",
      "client_id": "123456789",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk%40tu-project.iam.gserviceaccount.com"
    }
