apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meatmanager-ingress
  namespace: meatmanager
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - meatmanager.tudominio.com
      secretName: meatmanager-tls
  rules:
    - host: meatmanager.tudominio.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: meatmanager-api
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meatmanager-web
                port:
                  number: 80
