services:
  web-main:
    image: ${GHCR_NAMESPACE}/meatmanager-web:main
    container_name: meatmanager-web-main
    restart: unless-stopped
    networks:
      - shared_proxy

  api-main:
    image: ${GHCR_NAMESPACE}/meatmanager-api:main
    container_name: meatmanager-api-main
    restart: unless-stopped
    env_file:
      - ./env/api-main.env
    volumes:
      - ./secrets/firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - shared_proxy

  web-dev:
    image: ${GHCR_NAMESPACE}/meatmanager-web:dev
    container_name: meatmanager-web-dev
    restart: unless-stopped
    networks:
      - shared_proxy

  api-dev:
    image: ${GHCR_NAMESPACE}/meatmanager-api:dev
    container_name: meatmanager-api-dev
    restart: unless-stopped
    env_file:
      - ./env/api-dev.env
    volumes:
      - ./secrets/firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - shared_proxy

networks:
  shared_proxy:
    external: true
    name: gestionclientes_gestionclientes_net
